FROM ubuntu:focal
LABEL maintainer="myoung34@my.apsu.edu"

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

COPY --chmod=700 build/ /tmp/build/
RUN /tmp/build/install_base.sh

ENV GOROOT=/usr/local/go
ENV RUSTUP_HOME=/usr/local/rustup
ENV CARGO_HOME=/usr/local/cargo
ENV PATH=/usr/local/go/bin:/usr/local/cargo/bin:${PATH}
